image: golang:latest

before_script:
  - make install-deps

stages:
  - test
  - build

format:
  stage: test
  script:
    - make format

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - git fetch --tags
    - make build/local
  artifacts:
    paths:
      - build/*.bin
    expire_in: 1 day
