image: golang:latest

before_script:
  - make go/downloadDependencies

stages:
  - test
  - build

format:
  stage: test
  script:
    - make format

test:
  stage: test
  script:
    - make test

.build_template:
  stage: build
  before_script:
    - git fetch --tags
  artifacts:
    paths:
      - dist/*.zip
      - dist/checksums.txt
    expire_in: 1 day

build/dev:
  stage: build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 day
  except:
    - tags
    - develop
  script:
    - git fetch --tags
    - make build/dev

build/snapshot:
  extends: .build_template
  only:
    - develop
    - triggers
    - schedules
  script:
    - make build/snapshot

build/release:
  extends: .build_template
  only:
    - tags
  script:
    - make build/release
