# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make go/downloadDependencies
builds:
  - goos:
      - linux
      - windows
    goarch:
      - amd64
      - "386"

archives:
  -
    format: zip
    files:
    - LICENSE
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

