style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/hectorjsmith/git-versioner
options:
  commits:
    filters:
      Type:
        - feat
        - fix
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE

